FROM --platform=linux/amd64 node:16-alpine

LABEL version="1.0"
LABEL description="This is the base docker image for the GitHub Search frontend React app."
LABEL maintainer = ["muiboonyang@gmail.com"]

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install --production

COPY . .

EXPOSE 3000

CMD ["npm", "start"]