FROM --platform=linux/amd64 node:16-alpine as build

LABEL version="1.0"
LABEL description="This is the base docker image for the GitHub Search frontend React app."
LABEL maintainer = ["muiboonyang@gmail.com"]

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install --production

COPY . .

RUN npm run build

# ===================

FROM --platform=linux/amd64 nginx
COPY --from=build /app/build /usr/share/nginx/html

