version: "3"

services:
  backend:
    env_file: "backend/.env"
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    image: "github-search-backend-dev"
    ports:
      - "5001:5001"
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile.dev
    image: "github-search-frontend-dev"
    ports:
      - "3000:3000"
