version: "3"

services:
  backend:
    env_file: "backend/.env"
    build:
      context: backend
      dockerfile: ./Dockerfile.prod
    image: "github-search-backend-prod"
    ports:
      - "5050:5001"
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile.prod
    image: "github-search-frontend-prod"
    ports:
      - "6565:80" #nginx listens on 80
